# Generated by Django 2.1.1 on 2019-06-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名字')),
                ('birthday', models.DateField(verbose_name='出生年月日')),
                ('gender', models.IntegerField(choices=[(1, '男性'), (0, '女性')], verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('birth_place', models.CharField(max_length=64, verbose_name='籍贯')),
                ('address', models.CharField(max_length=256, verbose_name='家庭住址')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
